from jinja2 import Environment, BaseLoader
from weasyprint import HTML
import io
from ..models.schemas.report import ReportResponse

# Simple HTML template for the report
TEMPLATE_STR = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; line-height: 1.6; margin: 40px; }
        h1 { color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; }
        h3 { color: #7f8c8d; font-size: 1.1em; }
        .metadata { background: #f9f9f9; padding: 15px; border-radius: 5px; margin-bottom: 20px; font-size: 0.9em; }
        .section { margin-bottom: 40px; }
        ul { margin-top: 5px; }
        .footer { margin-top: 50px; font-size: 0.8em; text-align: center; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>
    <h1>Company Intelligence Report: {{ company.name }}</h1>
    
    <div class="metadata">
        <strong>Industry:</strong> {{ company.industry }}<br>
        <strong>Geographic Presence:</strong> {{ overview.geographic_presence | join(', ') if overview.geographic_presence else 'N/A' }}<br>
        <strong>Scale:</strong> {{ overview.scale if overview else 'N/A' }}<br>
        <strong>Generated:</strong> {{ completed_at }}
    </div>

    <div class="section">
        <h2>Company Overview</h2>
        <p>{{ overview.summary if overview else 'N/A' }}</p>
    </div>

    <div class="section">
        <h2>Business Information</h2>
        {% if biz %}
            <h3>Offerings</h3>
            <ul>
            {% for item in biz.offerings %}
                <li>{{ item }}</li>
            {% endfor %}
            </ul>
            <h3>Recent Developments</h3>
            <ul>
            {% for item in biz.developments %}
                <li>{{ item }}</li>
            {% endfor %}
            </ul>
            <h3>Expansion Plans</h3>
            <ul>
            {% for item in biz.expansion_plans %}
                <li>{{ item }}</li>
            {% endfor %}
            </ul>
        {% else %}
            <p>N/A</p>
        {% endif %}
    </div>

    <div class="section">
        <h2>Business Challenges</h2>
        {% if chal %}
            {% for item in chal.items %}
                <h3>{{ loop.index }}. {{ item.challenge }}</h3>
                <p><strong>Category:</strong> {{ item.category }} | <strong>Severity:</strong> {{ item.severity }}</p>
                <p>{{ item.reasoning }}</p>
            {% endfor %}
        {% else %}
            <p>N/A</p>
        {% endif %}
    </div>

    <div class="section">
        <h2>AI Opportunities</h2>
        {% if ai %}
            {% for item in ai.items %}
                <h3>{{ loop.index }}. {{ item.opportunity }}</h3>
                <p><strong>Category:</strong> {{ item.category }} | <strong>Impact:</strong> {{ item.impact }} | <strong>Effort:</strong> {{ item.effort }}</p>
                <p>{{ item.rationale }}</p>
            {% endfor %}
        {% else %}
            <p>N/A</p>
        {% endif %}
    </div>

    <div class="section">
        <h2>CEO Pitch</h2>
        <p>{{ pitch.content if pitch else 'N/A' }}</p>
    </div>

    <div class="footer">
        Generated by AI Research Agent | Confidential
    </div>
</body>
</html>
"""

class PDFService:
    def generate_pdf(self, report: ReportResponse) -> bytes:
        env = Environment(loader=BaseLoader())
        template = env.from_string(TEMPLATE_STR)
        
        sections = report.sections or {}
        
        html_out = template.render(
            company=report.company,
            completed_at=report.completed_at.strftime("%Y-%m-%d %H:%M:%S") if report.completed_at else "N/A",
            overview=sections.get("company_overview", {}),
            biz=sections.get("business_info", {}),
            chal=sections.get("challenges", {}),
            ai=sections.get("ai_opportunities", {}),
            pitch=sections.get("ceo_pitch", {})
        )
        
        pdf_bytes = HTML(string=html_out).write_pdf()
        return pdf_bytes
